// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvsrniqpxojcsflzxkcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2c3JuaXFweG9qY3NmbHp4a2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODk0MDMsImV4cCI6MjA2NTk2NTQwM30.qB1-20CC_QpjUP0DM8n6vsNEXMR2eLTIYYpen--X224";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);