// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hemgmpmxaszqmjtctard.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbWdtcG14YXN6cW1qdGN0YXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTA2MTEsImV4cCI6MjA2Mzc2NjYxMX0.n5LThJEW0iS_hFMoDZjMW_0Qm_9yKXq3gsnVGAv2K4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);